[tool.poetry]
name = "recoverpy"
version = "1.3.2"
description = "A TUI to recover overwritten or deleted data."
authors = ["PabloLec <pablo.lecolinet@gmail.com>"]
license = "GPL-3.0 License"
readme = "README.md"
homepage = "https://github.com/PabloLec/recoverpy"
repository = "https://github.com/PabloLec/recoverpy"
documentation = "https://github.com/PabloLec/recoverpy#readme"
keywords = ["data",
            "recovery",
            "search",
            "cli",
            "console",
            "cui",
            "tui",
            "terminal",
            "cybersec",
            "cybersecurity",
            "security",
            "pentesting",
            "grep",
            "linux",
            "unix"]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Operating System :: POSIX :: Linux",
        "Environment :: Console",
        "Intended Audience :: End Users/Desktop",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ]
include = ["recoverpy/config.yaml"]

[tool.poetry.dependencies]
python = "^3.6.2"
PyYAML = "^5.4.1"
py-cui = "^0.1.3"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
pytest = "^6.2.4"
pylint = "^2.11.1"
isort = "^5.9.3"
black = "^21.9b0"
flake8 = "^3.9.2"
pre-commit = "^2.15.0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.9.2"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.6.1"
darglint = "^1.8.0"
flake8-docstrings = "^1.6.0"
flake8-eradicate = "^1.1.0"
flake8-isort = "^4.0.0"
flake8-pytest-style = "^1.5.0"
flake8-mutable = "^1.2.0"
flake8-spellcheck = "^0.24.0"
flake8-html = "^0.4.1"

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "missing-docstring",
  "unused-argument",
  "no-value-for-parameter",
  "no-member",
  "no-else-return",
  "bad-whitespace",
  "bad-continuation",
  "line-too-long",
  "fixme",
  "protected-access",
  "too-few-public-methods",
]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
