name: Release on AUR

on: workflow_dispatch

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@2.6.0
        with:
          pkgname: python-recoverpy
          pkgbuild: ./PKGBUILD
          commit_username: PabloLec
          commit_email: pablolec@pm.me
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
