name: Upload Python Package to PyPI

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.2
      with:
          github_repo: PabloLec/recoverpy
          twine_username: ${{ secrets.TWINE_USERNAME }}
          twine_password: ${{ secrets.TWINE_PASSWORD }}
          verify_metadata: true
          skip_existing: true
          verbose: true
