name: Test release upload

on:
  workflow_dispatch:

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          poetry install
          sudo apt-get install progress
      - name: Run tests
        run: poetry run pytest
      - name: Publish
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish --build -r testpypi --dry-run
